# Generated by Django 4.0.3 on 2022-04-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_engine_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
